// ========================
// Enums
// ========================

export enum Role {
  STUDENT = 'STUDENT',
  FACULTY = 'FACULTY',
  ADMIN = 'ADMIN',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  COMPLIANCE_OFFICER = 'COMPLIANCE_OFFICER',
  REGULATOR = 'REGULATOR',
}

export enum Status {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  COMPLETED = 'COMPLETED',
}

export enum ExamType {
  MIDTERM = 'MIDTERM',
  FINAL = 'FINAL',
  QUIZ = 'QUIZ',
  ASSIGNMENT = 'ASSIGNMENT',
}

export enum GradeStatus {
  PASS = 'PASS',
  FAIL = 'FAIL',
  PENDING = 'PENDING',
  INCOMPLETE = 'INCOMPLETE',
}

export enum ProjectStatus {
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ThesisStatus {
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REVISION_REQUIRED = 'REVISION_REQUIRED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AuditStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FLAGGED = 'FLAGGED',
}

export enum Severity {
  INFO = 'INFO',
  WARN = 'WARN',
  ERROR = 'ERROR',
  CRITICAL = 'CRITICAL',
}

export enum ComplianceEntityType {
  STUDENT = 'STUDENT',
  FACULTY = 'FACULTY',
  DEPARTMENT = 'DEPARTMENT',
  COURSE = 'COURSE',
  CURRICULUM = 'CURRICULUM',
  EXAM = 'EXAM',
  THESIS = 'THESIS',
  RESEARCH_PROJECT = 'RESEARCH_PROJECT',
  STUDENT_DOCUMENT = 'STUDENT_DOCUMENT',
}

export enum ComplianceResult {
  // COMPLIANT = 'COMPLIANT',
  // NON_COMPLIANT = 'NON_COMPLIANT',
  // PARTIALLY_COMPLIANT = 'PARTIALLY_COMPLIANT',
  // UNDER_REVIEW = 'UNDER_REVIEW',
  // EXEMPTED = 'EXEMPTED',
    PASS = "PASS",
    FAIL = "FAIL",
    PENDING = "PENDING",
    DEFERRED = "DEFERRED",
    NOT_APPLICABLE = "NOT_APPLICABLE"
}

export enum DocumentType {
  IDPROOF = 'IDPROOF',
  TRANSCRIPT = 'TRANSCRIPT',
  MARKSSHEET = 'MARKSSHEET',
  CERTIFICATE = 'CERTIFICATE',
  OFFERLETTER = 'OFFERLETTER',
  BONAFIDE = 'BONAFIDE',
  FEE_RECEIPT = 'FEE_RECEIPT',
  OTHER = 'OTHER',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum NotificationType {
  ENROLLMENT = 'ENROLLMENT',
  COURSE = 'COURSE',
  EXAM = 'EXAM',
  RESEARCH = 'RESEARCH',
  COMPLIANCE = 'COMPLIANCE',
}

export enum ReportScope {
  DEPARTMENT = 'DEPARTMENT',
  INSTITUTION = 'INSTITUTION',
  FINANCIAL = 'FINANCIAL',
  COMPLIANCE = 'COMPLIANCE',
  ACADEMIC = 'ACADEMIC',
  RESEARCH = 'RESEARCH',
}

export enum ComplianceType {
  COURSE = 'COURSE',
  EXAM = 'EXAM',
  RESEARCH = 'RESEARCH'
}
