import { useState, useEffect } from 'react';
import { Modal } from 'react-bootstrap';
import { BsPlus, BsEye } from 'react-icons/bs';
import { toast } from 'react-toastify';
import { departmentService } from '@/services/department.service';
import { reportService } from '@/services/report.service';
import { useAuth } from '@/contexts/AuthContext';
import { DataTable } from '@/components/ui/DataTable';
import type { Column } from '@/components/ui/DataTable';
import { PageHeader } from '@/components/ui/PageHeader';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { Status } from '@/types/enums';
import type { Department } from '@/types/academic.types';
import type { Report, CreateReportRequest } from '@/types/compliance.types';
import type { ReportScope } from '@/types/enums';

type ModalMode = 'create' | 'view' | null;

export default function CompReports() {
  const { user } = useAuth();
  const [items, setItems] = useState<Report[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState<ModalMode>(null);
  const [selected, setSelected] = useState<Report | null>(null);
  const [saving, setSaving] = useState(false);

  const [scope, setScope] = useState('');
  const [metrics, setMetrics] = useState('');
  const [departmentId, setDepartmentId] = useState('');
  const [status, setStatus] = useState<Status>('ACTIVE' as Status);

  const load = async () => {
    setLoading(true);
    try {
      const reports = await reportService.getAll();
      setItems(reports);
    } catch (err: unknown) {
      const status = (err as { response?: { status?: number } })?.response?.status;
      if (status !== 404 && status !== 500) toast.error('Failed to load reports');
    }
    try {
      const depts = await departmentService.getAll();
      setDepartments(depts);
    } catch {
      // departments are supplementary; compliance officer may not have access
    }
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  const openCreate = () => { setScope(''); setMetrics(''); setDepartmentId(''); setStatus('ACTIVE' as Status); setModal('create'); };
  const openView   = (item: Report) => { setSelected(item); setModal('view'); };

  const handleCreate = async () => {
    setSaving(true);
    try {
      const payload: CreateReportRequest = {
        generatedBy: user?.id || '',
        departmentId, scope: scope as ReportScope, metrics, status,
      };
      await reportService.create(payload);
      toast.success('Report created'); setModal(null); load();
    } catch { toast.error('Failed to create report'); }
    finally { setSaving(false); }
  };

  const columns: Column<Report>[] = [
    { key: 'scope',      label: 'Scope' },
    { key: 'department', label: 'Department', render: item => String(item.department || '—') },
    { key: 'metrics',    label: 'Metrics',    render: item => item.metrics.length > 60 ? item.metrics.slice(0, 60) + '…' : item.metrics },
    { key: 'status',     label: 'Status',     render: item => <StatusBadge status={item.status} /> },
  ];

  return (
    <>
      <PageHeader title="Reports" subtitle="View and create reports"
        action={<button className="btn btn-primary btn-sm" onClick={openCreate}><BsPlus className="me-1" />Create Report</button>}
      />
      <DataTable columns={columns} data={items} loading={loading}
        actions={item => (
          <button className="icon-btn" onClick={() => openView(item)} title="View"><BsEye size={13} /></button>
        )}
      />

      <Modal show={modal === 'view'} onHide={() => setModal(null)} size="lg">
        <Modal.Header closeButton><Modal.Title>Report Details</Modal.Title></Modal.Header>
        <Modal.Body>
          {selected && (
            <div>
              <div className="grid grid-cols-2 gap-3.5 mb-3.5">
                <div>
                  <div className="text-xs font-bold text-secondary uppercase tracking-widest mb-1">Scope</div>
                  <div className="text-base">{selected.scope}</div>
                </div>
                <div>
                  <div className="text-xs font-bold text-secondary uppercase tracking-widest mb-1">Department</div>
                  <div className="text-base">{String(selected.department || '—')}</div>
                </div>
                <div>
                  <div className="text-xs font-bold text-secondary uppercase tracking-widest mb-1">Generated By</div>
                  <div className="text-base">{String(selected.generatedBy || '—')}</div>
                </div>
                <div>
                  <div className="text-xs font-bold text-secondary uppercase tracking-widest mb-1">Status</div>
                  <div><StatusBadge status={selected.status} /></div>
                </div>
              </div>
              <div>
                <div className="text-xs font-bold text-secondary uppercase tracking-widest mb-1.5">Metrics</div>
                <div className="bg-surface border border-border rounded p-3 text-base leading-relaxed">{selected.metrics}</div>
              </div>
            </div>
          )}
        </Modal.Body>
        <Modal.Footer>
          <button className="btn btn-secondary btn-sm" onClick={() => setModal(null)}>Close</button>
        </Modal.Footer>
      </Modal>

      <Modal show={modal === 'create'} onHide={() => setModal(null)} size="lg">
        <Modal.Header closeButton><Modal.Title>Create Report</Modal.Title></Modal.Header>
        <Modal.Body>
          <div className="grid grid-cols-2 gap-3.5 mb-3.5">
            <div>
              <label className="form-label">Scope</label>
              <select className="form-select" value={scope} onChange={e => setScope(e.target.value)}>
                <option value="">Select scope</option>
                <option value="DEPARTMENT">Department</option>
                <option value="INSTITUTION">Institution</option>
                <option value="FINANCIAL">Financial</option>
                <option value="COMPLIANCE">Compliance</option>
                <option value="ACADEMIC">Academic</option>
                <option value="RESEARCH">Research</option>
              </select>
            </div>
            <div>
              <label className="form-label">Department</label>
              <select className="form-select" value={departmentId} onChange={e => setDepartmentId(e.target.value)}>
                <option value="">Select department</option>
                {departments.map(d => <option key={d.id} value={d.id}>{d.departmentName}</option>)}
              </select>
            </div>
          </div>
          <div className="mb-3.5">
            <label className="form-label">Metrics</label>
            <textarea className="form-control" rows={5} value={metrics} onChange={e => setMetrics(e.target.value)} />
          </div>
          <div>
            <label className="form-label">Status</label>
            <select className="form-select" value={status} onChange={e => setStatus(e.target.value as Status)}>
              <option value="ACTIVE">Active</option>
              <option value="INACTIVE">Inactive</option>
            </select>
          </div>
        </Modal.Body>
        <Modal.Footer>
          <button className="btn btn-secondary btn-sm" onClick={() => setModal(null)}>Cancel</button>
          <button className="btn btn-primary btn-sm" onClick={handleCreate} disabled={saving}>
            {saving && <span className="spinner-border spinner-border-sm me-2" />}Save
          </button>
        </Modal.Footer>
      </Modal>
    </>
  );
}
